_target_: runners.mcp_runner.MCPClientRunner
args:
  server_params:
    _target_: mcp.StdioServerParameters
    command: python3
    args:
      - ../mcps/sqlite_server/main.py
      - --db-path 
      - ../.db/test.db
      - --cfg-name 
      - tools_config.json

  tool_calls:  # 工具调用列表（必须为标准列表格式，每个元素为字典）
    # 1. 列出表（空参数）
    - name: list_tables
      args: {}  # 空参数需显式为字典，不能省略

    # 2. 创建表（使用标准 YAML 列表和字典格式）
    - name: create_table
      args:
        table_name: test_local  # 表名（字符串）
        table_comment: 测试表
        columns: |
            user_id TEXT PRIMARY KEY NOT NULL,
            status TEXT DEFAULT '未知',
            timestamp DATETIME NOT NULL

    # 3. 描述表（传入表名参数）
    - name: describe_table
      args:
        table_name: test_local  # 表名字符串
    

    # 4. 插入数据（使用标准 YAML 列表和字典格式）
    - name: write_query
      args:
        table_name: test_local  # 非必填参数，可省略（根据工具配置，write_query 仅需 query）
        query: |
          INSERT INTO test_local (user_id, status, timestamp) 
          VALUES ('001', '在职', '2024-06-10 10:30:00')
    - name: write_query
      args:
        table_name: test_local  # 非必填参数，可省略（根据工具配置，write_query 仅需 query）
        query: |
          INSERT INTO test_local (user_id, status, timestamp) 
          VALUES ('002', '在职', '2024-06-10 10:30:00')
    
    - name: write_query
      args:
        table_name: test_local  # 非必填参数，可省略（根据工具配置，write_query 仅需 query）
        query: |
          INSERT INTO test_local (user_id, status, timestamp) 
          VALUES ('003', '离职', '2024-06-10 10:30:00')

    # 5. 查询数据（使用标准 YAML 列表和字典格式）
    - name: read_query
      args:
        query: "SELECT * FROM test_local WHERE status = '在职'"
    - name: read_query
      args:
        query: "SELECT * FROM test_local WHERE status = '离职'"

    # 6. 更新数据（使用标准 YAML 列表和字典格式）
    - name: write_query
      args:
        query: "UPDATE test_local SET status = '离职' WHERE user_id = '002'"
    - name: read_query
      args:
        query: "SELECT * FROM test_local"
    
    # 7. 删除数据（使用标准 YAML 列表和字典格式）
    - name: write_query
      args:
        query: "DELETE FROM test_local WHERE status = '离职'"
    - name: read_query
      args:
        query: "SELECT * FROM test_local"
    
    # 8. 删除表（危险操作，确保工具配置中 enabled: true）
    - name: drop_table
      args:
        table_name: test_local
    
    # 9. 再次列出表（验证表是否删除）
    - name: list_tables
      args: {}






