_target_: runners.mcp_runner.MCPClientRunner
args:
  server_params:
    _target_: mcp.StdioServerParameters
    command: python3
    args:
      - ../mcps/sqlite_server/main.py
      - --db-path 
      - ../.db/context.sqlite3
      - --cfg-name 
      - tools_config.json

  tool_calls:  
    # 1. 列出表（初始状态）
    - name: list_tables
      args: {}

    # 2. 创建OCR识别记录表
    - name: create_table
      args:
        table_name: ocr_recognition
        table_comment: OCR图像识别结果记录表
        columns: |
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            image_path TEXT UNIQUE NOT NULL,
            station_id TEXT NOT NULL,
            capture_time DATETIME NOT NULL,
            ocr_result TEXT NOT NULL,
            ocr_confidence INTEGER,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP

    # 3. 描述表结构
    - name: describe_table
      args:
        table_name: ocr_recognition

    # 4. 插入OCR识别记录
    - name: write_query
      args:
        query: |
          INSERT INTO ocr_recognition 
          (image_path, station_id, capture_time, ocr_result, ocr_confidence)
          VALUES ('/images/P001/20250611103000.jpg', 'P001', '2025-06-11 10:30:00', '当前水位: 102.5米', 95)

    - name: write_query
      args:
        query: |
          INSERT INTO ocr_recognition 
          (image_path, station_id, capture_time, ocr_result, ocr_confidence)
          VALUES ('/images/P002/20250611104500.jpg', 'P002', '2025-06-11 10:45:00', '设备温度: 32.5°C', 92)

    - name: write_query
      args:
        query: |
          INSERT INTO ocr_recognition 
          (image_path, station_id, capture_time, ocr_result)
          VALUES ('/images/P003/20250611110000.jpg', 'P003', '2025-06-11 11:00:00', '发电量: 2500kW/h')

    # 5. 查询所有OCR识别记录
    - name: read_query
      args:
        query: "SELECT * FROM ocr_recognition"

    # 6. 查询特定电站的OCR识别记录
    - name: read_query
      args:
        query: "SELECT * FROM ocr_recognition WHERE station_id = 'P001'"

    # 7. 查询特定时间范围的OCR识别记录
    - name: read_query
      args:
        query: "SELECT * FROM ocr_recognition WHERE capture_time BETWEEN '2025-06-11 10:00:00' AND '2025-06-11 11:00:00'"

    # 8. 查询置信度高于特定值的OCR识别记录
    - name: read_query
      args:
        query: "SELECT * FROM ocr_recognition WHERE ocr_confidence > 90"

    # 9. 尝试修改OCR识别记录（应该失败）
    - name: write_query
      args:
        query: "UPDATE ocr_recognition SET ocr_result = '修改后的结果' WHERE id = 1"

    # 10. 尝试删除OCR识别记录（应该失败）
    - name: write_query
      args:
        query: "DELETE FROM ocr_recognition WHERE id = 1"

    # 11. 验证数据完整性
    - name: read_query
      args:
        query: "SELECT * FROM ocr_recognition"

    # 12. 删除表（危险操作，仅用于演示）
    #- name: drop_table
    #  args:
    #    table_name: ocr_recognition

    # 13. 验证表已删除
    #- name: list_tables
    #  args: {}
